ad-deployment action

diff --git a/.github/workflows/ad-deployment.yml b/.github/workflows/ad-deployment.yml
--- a/.github/workflows/ad-deployment.yml
+++ b/.github/workflows/ad-deployment.yml
@@ -31,15 +31,14 @@ env:
   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
   ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
   ARM_USE_AZUREAD: true
+  ARM_SKIP_PROVIDER_REGISTRATION: true
 
 jobs:
-  terraform-plan:
-    name: Terraform Plan
-    if: github.event.inputs.terraform_task == 'plan'
+  terraform:
+    name: Terraform ${{ github.event.inputs.terraform_task }}
+    if: github.event.inputs.terraform_task != 'none'
     environment: dev
     runs-on: ubuntu-latest
-    env:
-      ARM_SKIP_PROVIDER_REGISTRATION: true
     defaults:
       run:
         working-directory: ./terraform/ad-deployment
@@ -57,28 +56,24 @@ jobs:
         id: init
         run: |
           terraform init \
-            -backend-config="resource_group_name=${{vars.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
-            -backend-config="storage_account_name=${{vars.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
-            -backend-config="container_name=${{vars.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}"
-
-      - name: tfsec
-        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
-        with:
-          tfsec_args: --soft-fail
-          github_token: ${{ github.token }}
+            -backend-config="resource_group_name=${{ vars.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
+            -backend-config="storage_account_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
+            -backend-config="container_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}"
 
       - name: Terraform Plan
         id: plan
+        if: github.event.inputs.terraform_task == 'plan' || github.event.inputs.terraform_task == 'apply'
         run: |
-          export exitcode=0
-          terraform plan -out main.tfplan || export exitcode=$?
+          terraform plan -out main.tfplan -detailed-exitcode || {
+            exitcode=$?
+            if [ $exitcode -eq 1 ]; then
+              echo "Terraform plan failed"
+              exit 1
+            else
+              echo "Terraform plan was successful"
+            fi
+          }
 
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-
-          if [ $exitcode -eq 1 ]; then
-            echo "Error: Terraform plan failed"
-            exit 1
-          else
-            echo "Terraform plan was successful"
-            exit 0
-          fi
+      - name: Terraform Apply
+        if: github.event.inputs.terraform_task == 'apply' && steps.plan.outcome == 'success'
+        run: terraform apply -auto-approve "main.tfplan"
